services:
  app:
    image: node:20-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev --name init && npm run dev"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./dev.db:/data/dev.db

volumes:
  sqlite_data:
